# Generated by Django 3.0.2 on 2020-01-04 20:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('limit', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_activated', models.DateField()),
                ('date_cancelled', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('incentive', models.TextField()),
                ('notes', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
