# Generated by Django 3.0.2 on 2020-01-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0005_auto_20200105_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='incentive',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
