# Generated by Django 3.0.2 on 2020-01-05 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0006_auto_20200105_0856'),
    ]

    operations = []
