# Generated by Django 3.0.2 on 2020-01-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0008_auto_20200111_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='date_reminder',
            field=models.DateField(blank=True, null=True),
        ),
    ]
