# Generated by Django 3.0.2 on 2020-01-12 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0010_creditcard_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='date_activated',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
