# Generated by Django 3.0.2 on 2020-01-16 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0011_auto_20200112_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='annualfee',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='limit',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
