# Generated by Django 3.0.2 on 2020-02-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20200127_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
